### ISSUE TITLE
Option to download Collection to local JSON file

### ISSUE THREAD

**Issue by pjhartzell** [gadomski/pc-rs#1]

**Comment by gadomski** [comment]
I added Item download in 0581fd0c2451215898843c2e307f9d9f259686ff. What's the use-case for the collection?

**Comment by pjhartzell** [comment]
Nice. I overlooked the Item download. Granted, Collection download is obscure, but I recently needed some Collections (and Items) in JSON form for ingest into a test pgstac database.

**Comment by gadomski** [comment]
I'm picturing:

```shell
pcdownload collection-id
```

to get a Collection, and:

```shell
pcdownload collection-id item-id --no-assets
```

for the Item only?
